export const sessions = [
  {
    id: '1',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '2',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '3',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '4',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '5',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '6',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '7',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '8',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
  {
    id: '9',
    sessions: [
      { day: 'Monday', idx: 'mon', hall: 1, time: '10:30', price: 80 },
      { day: 'Tuesday', idx: 'tues', hall: 1, time: '14:30', price: 120 },
      { day: 'Wednesday', idx: 'wed', hall: 1, time: '17:00', price: 120 },
      {
        day: 'Thursday',
        idx: 'thurs',
        hall: 1,
        time: '22:30',
        price: 80,
      },
      { day: 'Friday', idx: 'fri', hall: 1, time: '15:30', price: 140 },
      { day: 'Saturday', idx: 'sat', hall: 1, time: '14:00', price: 180 },
      { day: 'Sunday', idx: 'sun', hall: 1, time: '9:30', price: 100 },
    ],
  },
]
